#!/bin/sh

# Discord RPC
for i in {0..9}; do
    test -S "$XDG_RUNTIME_DIR"/discord-ipc-"$i" || ln -sf {app/com.discordapp.Discord,"$XDG_RUNTIME_DIR"}/discord-ipc-"$i";
done

env SDL_VIDEO_WAYLAND_WMCLASS=io.openrct2.OpenRCT2 SDL_VIDEO_X11_WMCLASS=io.openrct2.OpenRCT2 /app/bin/openrct2-wrapped "$@"
