name: OpenRCT2 develop build CI

on:
  repository_dispatch:
    types: ["openrct2_develop_push"]

jobs:
  change-commit:
    name: Change commit to latest upstream OpenRCT2 develop commit
    if: github.event.client_payload.commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
      - name: Change commit
        run: |
          sed -ri 's/^commit:\s.+$/commit: ${{ github.event.client_payload.commit }}/' openrct2-git.yml
      - name: Push change to beta branch
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "OpenRCT2 develop push trigger"
          git add openrct2-git.yml
          git commit -m "Update to commit ${{ github.event.client_payload.commit }}"
          git push
